### ISSUE TITLE
Installation on Laravel 7.6.2

### ISSUE THREAD

**Issue by dan-pascu** [adrianbarbos/mobilpay#10]
Hi,
I tried to install the package on Laravel 7.6.2 and looks like is not compatible:

_Conclusion: don't install adrianbarbos/mobilpay 1.0.11
Installation request for adrianbarbos/mobilpay ^1.0 -> satisfiable by adrianbarbos/mobilpay[1.0.0, 1.0.1, 1.0.10, 1.0.11, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9].
    - Conclusion: don't install laravel/framework v7.6.2_

I see that you updated the package but how can I make work on this version of Laravel.

Thank you

**Comment by danstoian07** [comment]
I just installed it yesterday on Laravel 7.8.1 and had no issues.
Try composer update, or maybe delete the vendor forlder and composer install.

**Comment by dan-pascu** [comment]
What version of thephpleague/omnipay are you using, 2.0 or 3.0 ?
I tried on version 3.0.

**Comment by dan-pascu** [comment]
I think I mixed the packages, I needed "adrianbarbos/omnipay-mobilpay" and I was trying to install "adrianbarbos/mobilpay" which is not for Omnipay. My bad.
