### ISSUE TITLE
Can't upgrade to Laravel 7 / 8

### ISSUE THREAD

**Issue by razvan-z** [adrianbarbos/mobilpay#13]
Hi Adrian!
Thanks again for your great work.
I'd like to upgrade my projects to the latest Laravel version, but I have an issue:

```
- Installation request for adrianbarbos/mobilpay =1.0.11 -> satisfiable by adrianbarbos/mobilpay[1.0.11].
- Conclusion: don't install laravel/framework v8.0.0
- adrianbarbos/mobilpay 1.0.11 requires illuminate/support 5.* || 6.* || 7.* -> satisfiable by laravel/framework[v6.20.6], illuminate/support[5.0.x-dev, [...], v7.9.2].
```

Would your library be compatible with `illuminate/support` v. 8.* ?

Thanks!

**Comment by adrianbarbos** [comment]
hey @razvan-z. Didn't test it with the new version, could work but I don't have a mobilpay account anymore to test and I'm not sure if mobilpay has some kind of developer account

**Comment by adrianbarbos** [comment]
@razvan-z a PR #14  was merged with Laravel 8 support, it should work now
