### ISSUE TITLE
Any update for Laravel 5.8.* ?

### ISSUE THREAD

**Issue by danstoian07** [adrianbarbos/mobilpay#3]
Using version ^1.0 for adrianbarbos/mobilpay
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install adrianbarbos/mobilpay 1.0.7
    - Conclusion: don't install adrianbarbos/mobilpay 1.0.6
    - Conclusion: don't install adrianbarbos/mobilpay 1.0.5
    - Conclusion: don't install adrianbarbos/mobilpay 1.0.4
    - Conclusion: don't install adrianbarbos/mobilpay 1.0.3
    - Conclusion: don't install adrianbarbos/mobilpay 1.0.2
    - Conclusion: don't install adrianbarbos/mobilpay 1.0.1
    - adrianbarbos/mobilpay 1.0.0 requires barryvdh/laravel-omnipay 0.2.*@dev -> satisfiable by barryvdh/laravel-omnipay[v0.2.0].
    - Conclusion: remove laravel/framework v5.8.29
    - Installation request for adrianbarbos/mobilpay ^1.0 -> satisfiable by adrianbarbos/mobilpay[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7].
    - Conclusion: don't install laravel/framework v5.8.29
    - barryvdh/laravel-omnipay v0.2.0 requires illuminate/support 5.0.* || 5.1.* || 5.2.* || 5.3.* || 5.4.* || 5.5.* -> satisfiable by illuminate/support[5.0.x-dev, 5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - don't install illuminate/support 5.1.x-dev|don't install laravel/framework v5.8.29
    - don't install illuminate/support 5.2.x-dev|don't install laravel/framework v5.8.29
    - don't install illuminate/support 5.3.x-dev|don't install laravel/framework v5.8.29
    - don't install illuminate/support 5.4.x-dev|don't install laravel/framework v5.8.29
    - don't install illuminate/support 5.5.x-dev|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.1.1|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.1.13|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.1.16|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.1.2|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.1.20|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.1.22|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.1.25|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.1.28|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.1.30|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.1.31|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.1.41|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.1.6|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.1.8|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.2.0|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.2.19|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.2.21|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.2.24|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.2.25|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.2.26|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.2.27|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.2.28|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.2.31|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.2.32|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.2.37|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.2.43|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.2.45|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.2.6|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.2.7|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.3.0|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.3.16|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.3.23|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.3.4|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.4.0|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.4.13|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.4.17|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.4.19|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.4.27|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.4.36|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.4.9|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.5.0|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.5.16|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.5.17|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.5.2|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.5.28|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.5.33|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.5.34|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.5.35|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.5.36|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.5.37|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.5.39|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.5.40|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.5.41|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.5.43|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.5.44|don't install laravel/framework v5.8.29
    - don't install illuminate/support 5.0.x-dev|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.0.0|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.0.22|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.0.25|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.0.26|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.0.28|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.0.33|don't install laravel/framework v5.8.29
    - don't install illuminate/support v5.0.4|don't install laravel/framework v5.8.29
    - Installation request for laravel/framework (locked at v5.8.29, required as 5.8.*) -> satisfiable by laravel/framework[v5.8.29].

Installation failed, reverting ./composer.json to its original content.

**Comment by adrianbarbos** [comment]
TBH i haven't used it in any 5.8 projects yet, will check asap and make an update.

**Comment by adrianbarbos** [comment]
@danstoian07 updated the package to 1.0.8 and tested it with a fresh laravel 5.8 + a mobilpay sandbox account and it worked as expected :)
